import {
  PropertyImagePreset,
  ChristmasPattern,
  OmniPattern,
  CustomerResidence,
  DecorOptions,
} from "@/types/lighting";

export const DEFAULT_CUSTOMER: CustomerResidence = {
  lastName: "Payne",
  residenceTitle: "THE PAYNE RESIDENCE",
  address: "4820 Highland Park Dr, Dallas, TX 75205",
  franchiseLocation: "Augusta Lights · DFW Central & North Texas",
  consultationDate: "October 14, 2026",
  initialBallparkQuote: 2850,
};

export const CHRISTMAS_PATTERNS: ChristmasPattern[] = [
  {
    id: "warm-white",
    name: "Warm White (Classic #1 Seller)",
    colorName: "2700K Architectural Warm White",
    palette: ["#ffdf9e"],
    colorDescriptions: "Pure 2700K golden architectural warm white. Our #1 residential seller across Texas.",
    isBestSeller: true,
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
  {
    id: "cool-white",
    name: "Cool White",
    colorName: "6000K Crisp Winter White",
    palette: ["#f8fafc"],
    colorDescriptions: "High-contrast modern winter white with ice-blue undertone.",
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
  {
    id: "candy-cane",
    name: "Candy Cane (2 Red / 2 White)",
    colorName: "Alternating 2-Bulb Repeating Groups",
    palette: ["#ef4444", "#ef4444", "#ffffff", "#ffffff"],
    colorDescriptions: "Festive holiday rhythm using authentic 2 Red / 2 Warm White commercial bulb groupings.",
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
  {
    id: "blue-white",
    name: "Winter Blue & White (2 Blue / 2 White)",
    colorName: "Cobalt Blue & Cool White",
    palette: ["#2563eb", "#2563eb", "#f8fafc", "#f8fafc"],
    colorDescriptions: "High-impact evening contrast featuring repeating pairs of cobalt blue and cool white.",
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
  {
    id: "red-green",
    name: "Red & Green Holiday Classic",
    colorName: "Crimson & Evergreen Repeating Groups",
    palette: ["#dc2626", "#dc2626", "#16a34a", "#16a34a"],
    colorDescriptions: "Traditional holiday pairing with 2 Red / 2 Green commercial LED bulb grouping.",
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
  {
    id: "vintage-multi",
    name: "Vintage 5-Color Jewel Tone",
    colorName: "Red, Amber, Green, Blue, Warm White",
    palette: ["#ef4444", "#f59e0b", "#10b981", "#3b82f6", "#ffdf9e"],
    colorDescriptions: "Nostalgic multi-color roofline installation with balanced jewel tones.",
    bulbType: "SMD C9 Commercial LED",
    spacingInches: 15,
  },
];

export const OMNI_PATTERNS: OmniPattern[] = [
  {
    id: "omni-warm-3000k",
    name: "Warm Architectural White (3000K)",
    colorName: "3000K Soft Amber Wall Wash",
    beamColor: "#fef3c7",
    ambientColor: "rgba(245, 158, 11, 0.45)",
    spacingInches: 8,
    wallWashReachPct: 78,
    description: "Vertical downward architectural beam washing brick/stone down to landscape beds.",
  },
  {
    id: "omni-cool-5000k",
    name: "Cool Architectural White (5000K)",
    colorName: "5000K Pure Daylight Architectural",
    beamColor: "#e0f2fe",
    ambientColor: "rgba(59, 130, 246, 0.35)",
    spacingInches: 8,
    wallWashReachPct: 78,
    description: "Clean modern wall wash emphasizing limestone, stucco, and contemporary architectural lines.",
  },
  {
    id: "omni-rgb-spectrum",
    name: "Omni Full Spectrum RGB",
    colorName: "Dynamic Multi-Hue Architectural Beam",
    beamColor: "#c084fc",
    ambientColor: "rgba(168, 85, 247, 0.45)",
    spacingInches: 8,
    wallWashReachPct: 82,
    description: "Static representation of permanent smart-controlled color scenes for game days and holidays.",
  },
  {
    id: "omni-texas-patriotic",
    name: "Texas Lone Star (Red & White)",
    colorName: "Patriotic Architectural Columns",
    beamColor: "#f87171",
    ambientColor: "rgba(239, 68, 68, 0.4)",
    spacingInches: 8,
    wallWashReachPct: 75,
    description: "Alternating facade wash bays in warm white and deep red.",
  },
];

export const PROPERTY_PRESETS: PropertyImagePreset[] = [
  {
    id: "texas-brick-two-story",
    name: "Texas Red Brick Two-Story",
    style: "Traditional Colonial Brick",
    description: "Two-story red brick home with prominent double front gables, driveway SUV, and mature oak tree.",
    architectureType: "2-Story Brick · Highland Park TX",
    hasVehicle: true,
    vehicleDescription: "Silver SUV parked on left driveway",
    hasTrashCans: false,
    rooflines: [
      {
        id: "rf-main-gable-left",
        name: "Main Front Left Gable Eave",
        points: [[22, 38], [34, 20], [46, 38]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 28,
      },
      {
        id: "rf-main-gable-right",
        name: "Upper Center Dormer Gable",
        points: [[50, 36], [58, 24], [66, 36]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 20,
      },
      {
        id: "rf-upper-eave-right",
        name: "Upper Right Wing Horizontal Eave",
        points: [[66, 36], [82, 36]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 16,
      },
      {
        id: "rf-garage-eave",
        name: "Lower Garage Front Eave",
        points: [[12, 60], [38, 60]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 24,
      },
      {
        id: "rf-porch-overhang",
        name: "Front Entry Portico Eave",
        points: [[46, 56], [56, 56]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 10,
      },
      {
        id: "rf-back-ridge",
        name: "Secondary Rear Ridge (Non-Front)",
        points: [[34, 18], [62, 18]],
        isFrontFacing: false,
        enabled: false,
        bulbCount: 22,
      },
    ],
    windows: [
      { id: "win-1", x: 26, y: 43, width: 7, height: 11, panes: 6 },
      { id: "win-2", x: 35, y: 43, width: 7, height: 11, panes: 6 },
      { id: "win-3", x: 54, y: 41, width: 8, height: 11, panes: 6 },
      { id: "win-4", x: 70, y: 41, width: 8, height: 11, panes: 6 },
      { id: "win-5", x: 68, y: 64, width: 9, height: 13, panes: 8 },
      { id: "win-6", x: 79, y: 64, width: 9, height: 13, panes: 8 },
    ],
    trees: [
      { id: "tree-left", name: "Front Left Live Oak", trunkX: 16, baseY: 85, canopyX: 16, canopyY: 52, radius: 14 },
    ],
    wreathAnchor: { x: 25, y: 55 }, // Above garage
    drivewayBounds: { startX: 10, startY: 65, endX: 38, endY: 96 },
  },
  {
    id: "suburban-ranch-driveway",
    name: "Texas Ranch w/ Driveway Vehicle",
    style: "Single-Story Ranch",
    description: "Single-story suburban Texas home with low-pitch front gables, trash cans by garage, and driveway sedan.",
    architectureType: "1-Story Ranch · Frisco TX",
    hasVehicle: true,
    vehicleDescription: "Dark sedan on right driveway apron",
    hasTrashCans: true,
    rooflines: [
      {
        id: "rf-ranch-center",
        name: "Center Living Room Gable",
        points: [[32, 44], [46, 28], [60, 44]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 26,
      },
      {
        id: "rf-ranch-left-wing",
        name: "Left Bedroom Horizontal Fascia",
        points: [[14, 44], [32, 44]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 18,
      },
      {
        id: "rf-ranch-garage",
        name: "Right Double-Garage Front Eave",
        points: [[60, 48], [86, 48]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 24,
      },
      {
        id: "rf-ranch-rear",
        name: "Rear Valley Ridge (Excluded)",
        points: [[46, 26], [70, 32]],
        isFrontFacing: false,
        enabled: false,
        bulbCount: 16,
      },
    ],
    windows: [
      { id: "win-r1", x: 18, y: 50, width: 10, height: 12, panes: 4 },
      { id: "win-r2", x: 36, y: 50, width: 8, height: 12, panes: 4 },
      { id: "win-r3", x: 48, y: 50, width: 8, height: 12, panes: 4 },
    ],
    trees: [
      { id: "tree-ranch-left", name: "Left Front Red Oak", trunkX: 12, baseY: 86, canopyX: 12, canopyY: 55, radius: 12 },
    ],
    wreathAnchor: { x: 73, y: 44 }, // Centered over garage doors
    drivewayBounds: { startX: 62, startY: 58, endX: 88, endY: 96 },
  },
  {
    id: "austin-hill-country-stone",
    name: "Austin Hill Country Limestone",
    style: "Modern Hill Country Transitional",
    description: "Cream limestone facade with steep modern dark bronze gables, native cedar accents, and zero driveway vehicles.",
    architectureType: "Modern Hill Country · Westlake TX",
    hasVehicle: false,
    hasTrashCans: false,
    rooflines: [
      {
        id: "rf-hill-steep-gable",
        name: "Steep Architectural Center Gable",
        points: [[36, 42], [50, 16], [64, 42]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 32,
      },
      {
        id: "rf-hill-left-shed",
        name: "Left Modern Shed Roofline",
        points: [[16, 36], [36, 42]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 18,
      },
      {
        id: "rf-hill-right-wing",
        name: "Right Master Suite Fascia",
        points: [[64, 42], [84, 42]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 20,
      },
      {
        id: "rf-hill-garage",
        name: "Lower Front Garage Eave",
        points: [[16, 58], [34, 58]],
        isFrontFacing: true,
        enabled: true,
        bulbCount: 16,
      },
    ],
    windows: [
      { id: "win-h1", x: 44, y: 46, width: 12, height: 16, panes: 8 },
      { id: "win-h2", x: 68, y: 48, width: 10, height: 14, panes: 6 },
      { id: "win-h3", x: 42, y: 25, width: 6, height: 8, panes: 4 },
      { id: "win-h4", x: 52, y: 25, width: 6, height: 8, panes: 4 },
    ],
    trees: [
      { id: "tree-hill-right", name: "Front Right Texas Mountain Laurel", trunkX: 86, baseY: 84, canopyX: 86, canopyY: 58, radius: 10 },
    ],
    wreathAnchor: { x: 50, y: 35 }, // Centered under main steep peak
    drivewayBounds: { startX: 14, startY: 66, endX: 36, endY: 96 },
  },
];

export const DEFAULT_DECOR: DecorOptions = {
  treeWraps: {
    enabled: true,
    lightType: "5mm Warm White Mini",
    placementNote: "Trunk and primary canopy branches wrapped to 8ft",
  },
  shrubs: {
    enabled: true,
    lightType: "5mm Warm White Mini",
    placementNote: "Warm white net lighting across front foundation hedges",
  },
  wreaths: {
    enabled: true,
    sizeInches: 48,
    placementNote: "48-inch lighted wreath centered under prominent front gable",
  },
  groundStakes: {
    enabled: true,
    location: "driveway",
    color: "#ffdf9e",
    placementNote: "C9 warm white ground stakes contouring driveway & walkway",
  },
};
